version: 2
updates:
  - package-ecosystem: npm
    directory: /
    schedule: { interval: weekly }
  - package-ecosystem: github-actions
    directory: /
    schedule: { interval: weekly }
  - package-ecosystem: terraform
    directories: [/infra/bootstrap, /infra/platform]
    schedule: { interval: weekly }
  - package-ecosystem: docker
    directory: /containers/nginx
    schedule: { interval: weekly }
